//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSwitchPort
    {
        public int ID { get; set; }
        public string SwitchName { get; set; }
        public string SwitchIP { get; set; }
        public string SwitchMAC { get; set; }
        public string SwitchPort { get; set; }
        public string DeviceIPName { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> AddDatetime { get; set; }
        public Nullable<System.DateTime> EditDatetime { get; set; }
        public string Remarks { get; set; }
    }
}
