//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryDataEntities2 : DbContext
    {
        public FactoryDataEntities2()
            : base("name=FactoryDataEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<DeviceSwitchPort> DeviceSwitchPort { get; set; }
        public virtual DbSet<NEWCCTVDATA> NEWCCTVDATA { get; set; }
        public virtual DbSet<NEWDOORDATA> NEWDOORDATA { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Account> Account { get; set; }
    }
}
