//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWCCTVDATA
    {
        public int ID { get; set; }
        public string CCTVNumber { get; set; }
        public string CCTVName { get; set; }
        public string CCTVIP { get; set; }
        public string CCTVMAC { get; set; }
        public string CCTVBrand { get; set; }
        public string CCTVModel { get; set; }
        public string CCTVType { get; set; }
        public string CCTVSwitchIp { get; set; }
        public string CCTVSwitchPort { get; set; }
        public string AddVendor { get; set; }
        public Nullable<System.DateTime> AddDatetime { get; set; }
        public Nullable<System.DateTime> EditDatetime { get; set; }
        public string Remarks { get; set; }
        public string Fab { get; set; }
    }
}
