//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWDOORDATA
    {
        public int ID { get; set; }
        public string DoorNumber { get; set; }
        public string DoorName { get; set; }
        public string DoorIstarControlName { get; set; }
        public string DoorConnectType { get; set; }
        public string DoorReaderType { get; set; }
        public string DoorAcmNumber { get; set; }
        public string DoorReaderPort { get; set; }
        public string AddVendor { get; set; }
        public Nullable<System.DateTime> AddDatetime { get; set; }
        public Nullable<System.DateTime> EditDatetime { get; set; }
        public string Remarks { get; set; }
        public string Fab { get; set; }
    }
}
