//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
        public string RackPeople { get; set; }
        public string RackVendor { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.DateTime> AddDatetime { get; set; }
        public Nullable<System.DateTime> EditDatetime { get; set; }
        public string FileName { get; set; }
    }
}
